### PR TITLE
browse()

### PR DESCRIPTION
**Pull request by btupper**
Adds browse() to facilitate user interaction with ERDDAP resources.  Disabled when not in interactive R session.

Thanks for rerddap!

### CODE REVIEW

**Comment by sckott** [comment]
thanks! will have a look

**Comment by sckott** [comment]
* You named the function `browse()`, but the eg. uses `ed_browse()` - which did you want to use?  
* don't need the `# browse.R` at the top of the file
* could you use `call. = FALSE` in the `stop()` method in `browse.deafult` ?  makes a cleaner error message
* could you show more examples? one for each of the class methods

**Comment by btupper** [comment]
Fixed as requested.  More important than what I think about the name is what you think about the name.  I'm ok either way; currently it is uniformly 'browse' (I hope!)

   
> On Feb 18, 2016, at 3:29 PM, Scott Chamberlain <notifications@github.com> wrote:
> 
> You named the function browse(), but the eg. uses ed_browse() - which did you want to use?
> don't need the # browse.R at the top of the file
> could you use call. = FALSE in the stop() method in browse.deafult ? makes a cleaner error message
> could you show more examples? one for each of the class methods
> —
> Reply to this email directly or view it on GitHub <https://github.com/ropensci/rerddap/pull/38#issuecomment-185901911>.
> 

Ben Tupper
Bigelow Laboratory for Ocean Sciences
60 Bigelow Drive, P.O. Box 380
East Boothbay, Maine 04544
http://www.bigelow.org

**Comment by sckott** [comment]
LGTM, thanks! I'll add your name as author

**Pull request merged**
